# Prometheus configuration for IDF My Buddy Travel Assistant

global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"

scrape_configs:
    # Prometheus itself
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    # Application metrics
    - job_name: "idf-buddy-app"
      static_configs:
          - targets: ["app-prod:8000"]
      metrics_path: "/metrics"
      scrape_interval: 30s
      scrape_timeout: 10s

    # Nginx metrics (if nginx-prometheus-exporter is used)
    - job_name: "nginx"
      static_configs:
          - targets: ["nginx:8080"]
      metrics_path: "/nginx_status"
      scrape_interval: 30s

    # PostgreSQL metrics (requires postgres_exporter)
    - job_name: "postgres"
      static_configs:
          - targets: ["postgres:5432"]
      scrape_interval: 30s

    # Redis metrics (requires redis_exporter)
    - job_name: "redis"
      static_configs:
          - targets: ["redis:6379"]
      scrape_interval: 30s

    # System metrics (requires node_exporter)
    - job_name: "node"
      static_configs:
          - targets: ["localhost:9100"]
      scrape_interval: 30s
